apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aso-demo
  namespace: argocd
  labels:
    demo: demo-2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Geertvdc/platformengineering-talk
    targetRevision: main
    path: demos/aso/samples
  destination:
    server: https://kubernetes.default.svc
    namespace: aso-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
