apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-appteam
  namespace: argocd
  labels:
    demo: demo-3
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/Geertvdc/platformengineering-talk
      targetRevision: main
      path: demos/crossplane/composition/appteam
    - repoURL: https://github.com/Geertvdc/platformengineering-talk
      targetRevision: main
      path: demos/crossplane/samples/appteam
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
