apiVersion: platform.demo.io/v1alpha1
kind: AppTeam
metadata:
  name: azurefest-team2
  namespace: crossplane-appteam-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  teamName: azurefest
  githubOrg: Geertvdc
