apiVersion: platform.demo.io/v1alpha1
kind: AppTeam
metadata:
  name: alpha-team
  namespace: crossplane-appteam-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  teamName: alpha
  githubOrg: Geertvdc
